version: '3.6'

services:

  airflow-webserver:
      image: ${REPO}
      container_name: airflow-webserver
      volumes:
        - ./dags:/opt/airflow/dags
        - ./sql:/opt/airflow/sql
      environment: 
        - AIRFLOW_HOME=/opt/airflow
        - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
        - AIRFLOW__CORE__EXECUTOR=${EXECUTOR}
        - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      ports:
        - "8080:8080"
      command: 'bash -c "airflow db init && airflow webserver -D && airflow scheduler -D"'

  source-db:
    image: postgres:11.4-alpine
    restart: always
    container_name: source-db
    ports:
      - "54320:54320"
    volumes:
      - ./mnt/mock-db/table_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${SOURCE_USER}
      - POSTGRES_PASSWORD=${SOURCE_PASSWORD}
      - POSTGRES_DB=${SOURCE_DB}

  dest-db:
    image: postgres:11.4-alpine
    restart: always
    container_name: dest-db
    ports:
      - "54321:54321"
    volumes:
      - ./mnt/mock-db/table_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DEST_USER}
      - POSTGRES_PASSWORD=${DEST_PASSWORD}
      - POSTGRES_DB=${DEST_DB}

  handler:
    image: python:3.8.7-buster
    container_name: handler
    depends_on:
      - source-db
      - dest-db
    volumes:
      - ./mnt/python-handler:/usr/src/app
    working_dir: /usr/src/app
    command: 'bash -c "pip3 install -r requirements.txt && tail -f /dev/null"'
